### ISSUE TITLE
ToDO finishing OER pt1

### ISSUE THREAD

**Issue by mikelovic** [CollectiveOpenSourceHardware/collectiveopensourcehardware.github.io#16]
- [ ] References/ list of literature
- [ ] H5P - image hotspot - adjust size
- [ ] add references for images 
- [ ] chapter - energy systems -> clean -> central vs. decentral!
- [ ] stepguide -> THT, testing part -> more detailed
- [ ] calculation list, costs for reproduction!
